- name: Configure Kubernetes Cluster
  hosts: k8s
  tasks:
    - name: Install required tools
      yum:
        name: 
          - docker
          - kubectl
          - kubeadm
        state: present

    - name: Initialize Kubernetes Cluster
      shell: kubeadm init --apiserver-advertise-address={{ ansible_host }}

    - name: Create kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
